### ISSUE TITLE
No more gRPC?

### ISSUE THREAD

**Issue by safinn** [EwanValentine/shippy#2]
Hey, great posts by the way. Just to be clear, from tutorial-2, gRPC is not longer being used and was replaced fully by go-micro?

**Comment by EwanValentine** [comment]
@safinn  - Thank you! We're still using gRPC under the hood, but go-micro wraps a framework around gRPC to make it a bit easier to communicate between services. 

Biggest bonus of using go-micro is the service discovery part. So instead of writing code to connect to, say: `http://127.0.0.1:50051`, go-micro stores a record of the address and allows you to give it a name. So instead you can do `my.serv`. So if the IP address or port changes, you don't need to update your services to use the new ip address. 

I hope this helps and sorry for the delayed response!

**Comment by karesh** [comment]
We can use kubernetes and istio for those purpose. What we need go-micro ?
If we have multiple docker running with the same service on different hosts. How go-micro knows those services ?  i doubt because its just a library..

**Comment by EwanValentine** [comment]
"We can use kubernetes and istio for those purpose" - you could do, and we are using Kubernetes as well for that purpose. Go-micro is using Kubernetes's DNS/service resolution under the hood. We could not use go-micro, but if we wanted to use something other than Kubernetes, so Consul, or Etcd, we'd likely have to change our code. Go 

"How go-micro knows those services ? i doubt because its just a library.." - It is just a library, but it hooks into whatever cloud platform you're running in order to abstract away the boilerplate code for resolving and connecting to services, using message brokers, logging, tracing etc. 

We're only using go-micro for service discovery at the moment. Go-micro has loads of cool features, and I'll be covering some more of those in the next few posts. 

I'm not sure, would you folks have preferred if I'd have stuck with just gRPC and hadn't covered go-micro? I could do some separate posts maybe?

**Comment by EwanValentine** [comment]
Take a look at some of the plugins go-micro has, some cool stuff :) 

https://github.com/micro/go-plugins

**Comment by karesh** [comment]
Thanks. 
From my point of view go-micro is just one choice of doing it. I feel have another post without go micro would be great for people who doesn't want libraries to do and we will have full control of our application.
