### ISSUE TITLE
Tutorial 3 Issue

### ISSUE THREAD

**Issue by haydursek** [EwanValentine/shippy#7]
Hi,

I just want to say first of all this is an awesome series, and really helping me get up to speed with GO and the framework.  I've been following along exactly, but seems to have hit a stumbling block in tutorial 3. I am able to get the services and client cli up and running, but I get an error from the consignment-service to the vessel-service, in that the vessel service cannot be found.

I have verified that the vessel service is coming up properly on the correct port and is even writing the initial vessel into MongoDB, but it just cannot be looked up from the consignment service. I have tried running everything in docker-compose, as individual docker containers, and even just starting them directly from the command line after compilation, but still the same issue in all 3 scenarios.

Looking for some pointers as to what you think the cause may be ?

**Comment by salehinRafi** [comment]
> "in order to run $dep ensure or $go get, you will need to ensure you have your code pushed up to Git so that it can pull in the vessel-service for example. " - said EwanValentine on Tutorial part 2.

In order to ensure that `$dep ensure` or `$go get` command can run in Dockerfile when you are running docker-compose,
1. You need to push your code to your git so that `dep `can pull the services you created.
2. In local, we install our created package by running `$go get github.com/<your-github-name>/<you-project-name>`
3. Import the package like the tutorial showed at all the required file. In our case:
`pb "github.com/<your-github-name>/<you-project-name>/consignment-service/proto/consignment"`
`vesselProto "github.com/<your-github-name>/<you-project-name>/vessel-service/proto/vessel".`
